scram::gui::MainWindow Class Reference
scram::gui::MainWindow Class Reference
#include <mainwindow.h>
Signals
void configChanged ()
Indicates addition of new input or configuration files.
Public Member Functions
MainWindow (QWidget *parent=nullptr)
bool setConfig (const std::string &configPath, std::vector< std::string > inputFiles={})
Loads a model and analysis configuration from a file.
bool addInputFiles (const std::vector< std::string > &inputFiles)
Adds a new set of model elements from input files.
template<>
mef::FaultTree * getFaultTree (mef::Gate *gate)
Specialization to find the fault tree container of a gate.
template<>
void removeEvent (model::Gate *event, mef::FaultTree *faultTree)
Specialization to deal with complexities of gate/fault-tree removal.
template<>
mef::FormulaPtr extract (const EventDialog &dialog)
Specialization to construct formula out of event editor data.
template<>
mef::BasicEventPtr extract (const EventDialog &dialog)
Specialization to construct basic event out of event editor data.
template<>
mef::HouseEventPtr extract (const EventDialog &dialog)
Specialization to construct house event out of event editor data.
template<>
mef::GatePtr extract (const EventDialog &dialog)
Specialization to construct gate out of event editor data.
Detailed Description
Todo:
Static build issues if the header is included.
Definition at line 55 of file mainwindow.h.
Constructor & Destructor Documentation
scram::gui::MainWindow::MainWindow (QWidget * parent = nullptr) explicit
Parameters
[in,out] parent The optional owner of this object.
Definition at line 154 of file mainwindow.cpp.
References GUI_ASSERT, and scram::gui::Validator::percent().
Member Function Documentation
bool scram::gui::MainWindow::setConfig (const std::string & configPath, std::vector< std::string > inputFiles = {})
Loads a model and analysis configuration from a file.
Parameters
[in] configPath The path to the configuration file.
[in] inputFiles Additional input files for model initialization.
Returns
true if the initialization is successful.
Postcondition
No side effects are left-over if the initialization is not successful.
Definition at line 261 of file mainwindow.cpp.
References addInputFiles().
Referenced by main().
bool scram::gui::MainWindow::addInputFiles (const std::vector< std::string > & inputFiles)
Adds a new set of model elements from input files.
Parameters
[in] inputFiles Paths to input files.
Returns
true if the addition is successful.
Postcondition
If the addition of any file is not successful, the model is left in its original state as if this function had not been called (i.e., transactional).
Definition at line 287 of file mainwindow.cpp.
References configChanged(), GUI_ASSERT, scram::gui::ZoomableView::zoomBestFit(), and scram::gui::ZoomableView::zoomChanged().
Referenced by main(), and setConfig().
template<> mef::FaultTree* scram::gui::MainWindow::getFaultTree (mef::Gate * gate)
Specialization to find the fault tree container of a gate.
Parameters
[in] gate The gate belonging exactly to one fault tree.
Returns
The fault tree container with the given gate.
Todo:
Duplicate code from EventDialog.
Definition at line 995 of file mainwindow.cpp.
References GUI_ASSERT.
template<> mef::FormulaPtr scram::gui::MainWindow::extract (const EventDialog & dialog)
Specialization to construct formula out of event editor data.
Parameters
[in] dialog The valid event dialog with data for a gate formula.
Returns
A new formula with arguments from the event dialog.
Todo:
Add into the parent undo.
Definition at line 1127 of file mainwindow.cpp.
References scram::gui::EventDialog::arguments(), scram::gui::EventDialog::connective(), and scram::gui::EventDialog::voteNumber().
The documentation for this class was generated from the following files:
mainwindow.h
mainwindow.cpp