scram::mef::Model Class Reference
scram::mef::Model Class Reference
This class represents a risk analysis model.
#include <model.h>
Public Member Functions
Model (std::string name="")
Creates a model container.
bool HasDefaultName () const
const std::string & GetOptionalName () const
void SetOptionalName (std::string name="")
Sets the optional name of the model.
Context * context () const
Formula::EventArg GetEvent (const std::string &id)
Convenience function to retrieve an event with its ID.
const ElementTable< InitiatingEventPtr > & initiating_events () const
const ElementTable< EventTreePtr > & event_trees () const
const ElementTable< SequencePtr > & sequences () const
const ElementTable< RulePtr > & rules () const
const ElementTable< FaultTreePtr > & fault_trees () const
const ElementTable< AlignmentPtr > & alignments () const
const ElementTable< SubstitutionPtr > & substitutions () const
const IdTable< ParameterPtr > & parameters () const
const MissionTime & mission_time () const
MissionTime & mission_time ()
const IdTable< HouseEventPtr > & house_events () const
const IdTable< BasicEventPtr > & basic_events () const
const IdTable< GatePtr > & gates () const
const IdTable< CcfGroupPtr > & ccf_groups () const
const ElementTable< std::unique_ptr< ExternLibrary > > & libraries () const
const ElementTable< ExternFunctionPtr > & extern_functions () const
void Add (InitiatingEventPtr element)
Adds MEF constructs into the model container.
void Add (EventTreePtr element)
Adds MEF constructs into the model container.
void Add (SequencePtr element)
Adds MEF constructs into the model container.
void Add (RulePtr element)
Adds MEF constructs into the model container.
void Add (FaultTreePtr element)
Adds MEF constructs into the model container.
void Add (AlignmentPtr element)
Adds MEF constructs into the model container.
void Add (SubstitutionPtr element)
Adds MEF constructs into the model container.
void Add (ParameterPtr element)
Adds MEF constructs into the model container.
void Add (HouseEventPtr element)
Adds MEF constructs into the model container.
void Add (BasicEventPtr element)
Adds MEF constructs into the model container.
void Add (GatePtr element)
Adds MEF constructs into the model container.
void Add (CcfGroupPtr element)
Adds MEF constructs into the model container.
void Add (std::unique_ptr< Expression > element)
Adds MEF constructs into the model container.
void Add (std::unique_ptr< Instruction > element)
Adds MEF constructs into the model container.
void Add (std::unique_ptr< ExternLibrary > element)
Adds MEF constructs into the model container.
void Add (ExternFunctionPtr element)
Adds MEF constructs into the model container.
HouseEventPtr Remove (HouseEvent *element)
Removes MEF constructs from the model container.
BasicEventPtr Remove (BasicEvent *element)
Removes MEF constructs from the model container.
GatePtr Remove (Gate *element)
Removes MEF constructs from the model container.
FaultTreePtr Remove (FaultTree *element)
Removes MEF constructs from the model container.
Public Member Functions inherited from scram::mef::Element
Element (std::string name)
Constructs an element with an original name.
const std::string & name () const
const std::string & label () const
void label (std::string label)
Sets the label.
const std::vector< Attribute > & attributes () const
void AddAttribute (Attribute attr)
Adds an attribute to the attribute map.
void SetAttribute (Attribute attr)
Sets an attribute to the attribute map.
bool HasAttribute (const std::string &name) const
Checks if the element has a given attribute.
const Attribute & GetAttribute (const std::string &name) const
bool RemoveAttribute (const std::string &name)
Removes the attribute of the element.
Static Public Attributes
static const char kDefaultName [] = "__unnamed-model__"
Only Model is allowed to have an optional name, while all other Elements require names.
Additional Inherited Members
Protected Member Functions inherited from scram::mef::Element
void name (std::string name)
Resets the element name.
Detailed Description
This class represents a risk analysis model.
Definition at line 43 of file model.h.
Constructor & Destructor Documentation
scram::mef::Model::Model (std::string name = "") explicit
Creates a model container.
Parameters
[in] name The optional name for the model.
Exceptions
ValidityError The name is malformed.
Definition at line 31 of file model.cc.
Member Function Documentation
bool scram::mef::Model::HasDefaultName () const inline
Returns
true if the model name has not been set.
Definition at line 59 of file model.h.
References kDefaultName, and scram::mef::Element::name().
Referenced by GetOptionalName(), scram::Reporter::ReportCalculatedQuantity< core::RiskAnalysis >(), and scram::mef::Serialize().
const std::string& scram::mef::Model::GetOptionalName () const inline
Returns
The model name or an empty string for the optional name.
Definition at line 62 of file model.h.
References HasDefaultName(), and scram::mef::Element::name().
Context* scram::mef::Model::context () const inline
Returns
The context to be used by test-event expressions for event-tree walks.
Note
There's only single context for the whole model (i.e., global); two event-trees cannot be walked concurrently.
Definition at line 77 of file model.h.
Referenced by scram::core::RiskAnalysis::Analyze().
const ElementTable<InitiatingEventPtr>& scram::mef::Model::initiating_events () const inline
Returns
Defined constructs in the model.
Definition at line 81 of file model.h.
Referenced by scram::core::RiskAnalysis::Analyze(), scram::Reporter::ReportCalculatedQuantity< core::RiskAnalysis >(), and scram::mef::Serialize().
const ElementTable<EventTreePtr>& scram::mef::Model::event_trees () const inline
Returns
Defined constructs in the model.
Definition at line 84 of file model.h.
Referenced by scram::Reporter::ReportCalculatedQuantity< core::RiskAnalysis >(), and scram::mef::Serialize().
const ElementTable<SequencePtr>& scram::mef::Model::sequences () const inline
Returns
Defined constructs in the model.
Definition at line 85 of file model.h.
Referenced by scram::Reporter::ReportCalculatedQuantity< core::RiskAnalysis >(), and scram::mef::Serialize().
const ElementTable<RulePtr>& scram::mef::Model::rules () const inline
Returns
Defined constructs in the model.
Definition at line 86 of file model.h.
Referenced by scram::Reporter::ReportCalculatedQuantity< core::RiskAnalysis >(), and scram::mef::Serialize().
const ElementTable<FaultTreePtr>& scram::mef::Model::fault_trees () const inline
Returns
Defined constructs in the model.
Definition at line 87 of file model.h.
Referenced by scram::core::RiskAnalysis::Analyze(), scram::Reporter::ReportCalculatedQuantity< core::RiskAnalysis >(), and scram::mef::Serialize().
const ElementTable<AlignmentPtr>& scram::mef::Model::alignments () const inline
Returns
Defined constructs in the model.
Definition at line 88 of file model.h.
Referenced by scram::core::RiskAnalysis::Analyze().
const ElementTable<SubstitutionPtr>& scram::mef::Model::substitutions () const inline
Returns
Defined constructs in the model.
Definition at line 89 of file model.h.
Referenced by scram::Reporter::ReportCalculatedQuantity< core::RiskAnalysis >().
const IdTable<ParameterPtr>& scram::mef::Model::parameters () const inline
Returns
Defined constructs in the model.
Definition at line 92 of file model.h.
Referenced by scram::Reporter::ReportCalculatedQuantity< core::RiskAnalysis >(), and scram::mef::Serialize().
const MissionTime& scram::mef::Model::mission_time () const inline
Returns
Defined constructs in the model.
Definition at line 93 of file model.h.
Referenced by scram::core::RiskAnalysis::Analyze().
MissionTime& scram::mef::Model::mission_time () inline
Returns
Defined constructs in the model.
Definition at line 94 of file model.h.
const IdTable<HouseEventPtr>& scram::mef::Model::house_events () const inline
Returns
Defined constructs in the model.
Definition at line 95 of file model.h.
Referenced by scram::core::RiskAnalysis::Analyze(), GetEvent(), scram::Reporter::ReportCalculatedQuantity< core::RiskAnalysis >(), and scram::mef::Serialize().
const IdTable<BasicEventPtr>& scram::mef::Model::basic_events () const inline
Returns
Defined constructs in the model.
Definition at line 96 of file model.h.
Referenced by GetEvent(), scram::Reporter::ReportCalculatedQuantity< core::RiskAnalysis >(), and scram::mef::Serialize().
const IdTable<GatePtr>& scram::mef::Model::gates () const inline
Returns
Defined constructs in the model.
Definition at line 97 of file model.h.
Referenced by GetEvent(), and scram::Reporter::ReportCalculatedQuantity< core::RiskAnalysis >().
const IdTable<CcfGroupPtr>& scram::mef::Model::ccf_groups () const inline
Returns
Defined constructs in the model.
Definition at line 98 of file model.h.
Referenced by scram::Reporter::ReportCalculatedQuantity< core::RiskAnalysis >(), and scram::mef::Serialize().
const ElementTable<std::unique_ptr<ExternLibrary> >& scram::mef::Model::libraries () const inline
Returns
Defined constructs in the model.
Definition at line 99 of file model.h.
Referenced by scram::Reporter::ReportCalculatedQuantity< core::RiskAnalysis >().
const ElementTable<ExternFunctionPtr>& scram::mef::Model::extern_functions () const inline
Returns
Defined constructs in the model.
Definition at line 102 of file model.h.
References Add().
Referenced by scram::Reporter::ReportCalculatedQuantity< core::RiskAnalysis >().
void scram::mef::Model::Add (InitiatingEventPtr element)
Adds MEF constructs into the model container.
Parameters
[in] element An element defined in this model.
Exceptions
RedefinitionError The element is already defined in the model.
Definition at line 35 of file model.cc.
Referenced by Add(), and extern_functions().
void scram::mef::Model::Add (EventTreePtr element)
Adds MEF constructs into the model container.
Parameters
[in] element An element defined in this model.
Exceptions
RedefinitionError The element is already defined in the model.
Definition at line 41 of file model.cc.
void scram::mef::Model::Add (SequencePtr element)
Adds MEF constructs into the model container.
Parameters
[in] element An element defined in this model.
Exceptions
RedefinitionError The element is already defined in the model.
Definition at line 46 of file model.cc.
void scram::mef::Model::Add (RulePtr element)
Adds MEF constructs into the model container.
Parameters
[in] element An element defined in this model.
Exceptions
RedefinitionError The element is already defined in the model.
Definition at line 51 of file model.cc.
void scram::mef::Model::Add (FaultTreePtr element)
Adds MEF constructs into the model container.
Parameters
[in] element An element defined in this model.
Exceptions
RedefinitionError The element is already defined in the model.
Definition at line 56 of file model.cc.
void scram::mef::Model::Add (AlignmentPtr element)
Adds MEF constructs into the model container.
Parameters
[in] element An element defined in this model.
Exceptions
RedefinitionError The element is already defined in the model.
Definition at line 61 of file model.cc.
void scram::mef::Model::Add (SubstitutionPtr element)
Adds MEF constructs into the model container.
Parameters
[in] element An element defined in this model.
Exceptions
RedefinitionError The element is already defined in the model.
Definition at line 66 of file model.cc.
void scram::mef::Model::Add (ParameterPtr element)
Adds MEF constructs into the model container.
Parameters
[in] element An element defined in this model.
Exceptions
RedefinitionError The element is already defined in the model.
Definition at line 71 of file model.cc.
References SCRAM_THROW.
void scram::mef::Model::Add (HouseEventPtr element)
Adds MEF constructs into the model container.
Parameters
[in] element An element defined in this model.
Exceptions
RedefinitionError The element is already defined in the model.
Definition at line 82 of file model.cc.
void scram::mef::Model::Add (BasicEventPtr element)
Adds MEF constructs into the model container.
Parameters
[in] element An element defined in this model.
Exceptions
RedefinitionError The element is already defined in the model.
Definition at line 87 of file model.cc.
void scram::mef::Model::Add (GatePtr element)
Adds MEF constructs into the model container.
Parameters
[in] element An element defined in this model.
Exceptions
RedefinitionError The element is already defined in the model.
Definition at line 92 of file model.cc.
void scram::mef::Model::Add (CcfGroupPtr element)
Adds MEF constructs into the model container.
Parameters
[in] element An element defined in this model.
Exceptions
RedefinitionError The element is already defined in the model.
Definition at line 97 of file model.cc.
void scram::mef::Model::Add (std::unique_ptr< Expression > element) inline
Adds MEF constructs into the model container.
Parameters
[in] element An element defined in this model.
Exceptions
RedefinitionError The element is already defined in the model.
Definition at line 126 of file model.h.
void scram::mef::Model::Add (std::unique_ptr< Instruction > element) inline
Adds MEF constructs into the model container.
Parameters
[in] element An element defined in this model.
Exceptions
RedefinitionError The element is already defined in the model.
Definition at line 129 of file model.h.
References Add(), GetEvent(), and Remove().
void scram::mef::Model::Add (std::unique_ptr< ExternLibrary > element)
Adds MEF constructs into the model container.
Parameters
[in] element An element defined in this model.
Exceptions
RedefinitionError The element is already defined in the model.
Definition at line 102 of file model.cc.
void scram::mef::Model::Add (ExternFunctionPtr element)
Adds MEF constructs into the model container.
Parameters
[in] element An element defined in this model.
Exceptions
RedefinitionError The element is already defined in the model.
Definition at line 107 of file model.cc.
Formula::EventArg scram::mef::Model::GetEvent (const std::string & id)
Convenience function to retrieve an event with its ID.
Parameters
[in] id The valid ID string of the event.
Returns
The event with its type encoded in variant suitable for formulas.
Exceptions
UndefinedElement The event with the given ID is not in the model.
Definition at line 113 of file model.cc.
References basic_events(), gates(), house_events(), and SCRAM_THROW.
Referenced by Add().
HouseEventPtr scram::mef::Model::Remove (HouseEvent * element)
Removes MEF constructs from the model container.
Parameters
[in] element An element defined in this model.
Returns
The removed element.
Exceptions
UndefinedElement The element cannot be found.
Definition at line 141 of file model.cc.
Referenced by Add().
BasicEventPtr scram::mef::Model::Remove (BasicEvent * element)
Removes MEF constructs from the model container.
Parameters
[in] element An element defined in this model.
Returns
The removed element.
Exceptions
UndefinedElement The element cannot be found.
Definition at line 145 of file model.cc.
GatePtr scram::mef::Model::Remove (Gate * element)
Removes MEF constructs from the model container.
Parameters
[in] element An element defined in this model.
Returns
The removed element.
Exceptions
UndefinedElement The element cannot be found.
Definition at line 149 of file model.cc.
FaultTreePtr scram::mef::Model::Remove (FaultTree * element)
Removes MEF constructs from the model container.
Parameters
[in] element An element defined in this model.
Returns
The removed element.
Exceptions
UndefinedElement The element cannot be found.
Definition at line 151 of file model.cc.
References scram::mef::Element::name(), and SCRAM_THROW.
Member Data Documentation
const char scram::mef::Model::kDefaultName = "__unnamed-model__" static
Only Model is allowed to have an optional name, while all other Elements require names.
An empty name is an error for Element class invariants as well. This leads to a nasty magic string based optional name for a model.
Definition at line 49 of file model.h.
Referenced by HasDefaultName().
The documentation for this class was generated from the following files:
model.h
model.cc