scram::mef::Formula Class Reference
scram::mef::Formula Class Reference
Boolean formula with operators and arguments.
#include <event.h>
Public Types
using EventArg = std::variant< Gate *, BasicEvent *, HouseEvent * >
Event arguments of a formula.
Public Member Functions
Formula (Operator type)
Constructs a formula.
Operator type () const
int vote_number () const
void vote_number (int number)
Sets the vote number only for an "atleast" formula.
int num_args () const
void AddArgument (EventArg event_arg)
Adds an event into the arguments list.
void AddArgument (FormulaPtr formula)
Adds a formula into the arguments list.
void RemoveArgument (EventArg event_arg)
Removes an event from the formula.
void Validate () const
Checks if a formula is initialized correctly with the number of arguments.
const std::vector< EventArg > & event_args () const
const std::vector< FormulaPtr > & formula_args () const
Detailed Description
Boolean formula with operators and arguments.
Formulas are not expected to be shared.
Definition at line 227 of file event.h.
Constructor & Destructor Documentation
scram::mef::Formula::Formula (Operator type) explicit
Constructs a formula.
Parameters
[in] type The logical operator for this Boolean formula.
Definition at line 70 of file event.cc.
Member Function Documentation
Operator scram::mef::Formula::type () const inline
Returns
The type of this formula.
Definition at line 238 of file event.h.
Referenced by scram::core::Pdag::AddArg(), scram::core::EventTreeAnalysis::EventTreeAnalysis(), and scram::mef::Serialize().
int scram::mef::Formula::vote_number () const
Returns
The vote number if and only if the formula is "atleast".
Exceptions
LogicError The vote number is not yet assigned.
Definition at line 72 of file event.cc.
References SCRAM_THROW.
Referenced by scram::core::Pdag::AddArg(), and scram::mef::Serialize().
void scram::mef::Formula::vote_number (int number)
Sets the vote number only for an "atleast" formula.
Parameters
[in] number The vote number.
Exceptions
ValidityError The vote number is invalid.
LogicError The vote number is assigned illegally.
Note
(Children number > vote number) should be checked outside of this class.
Definition at line 78 of file event.cc.
References scram::mef::kOperatorToString, scram::mef::kVote, and SCRAM_THROW.
const std::vector<EventArg>& scram::mef::Formula::event_args () const inline
Returns
The arguments of this formula of specific type.
Definition at line 258 of file event.h.
Referenced by scram::core::Pdag::AddArg(), scram::mef::FaultTree::CollectTopEvents(), scram::core::EventTreeAnalysis::EventTreeAnalysis(), scram::mef::cycle::GetNodes(), and scram::mef::Serialize().
const std::vector<FormulaPtr>& scram::mef::Formula::formula_args () const inline
Returns
The arguments of this formula of specific type.
Definition at line 259 of file event.h.
Referenced by scram::core::Pdag::AddArg(), scram::mef::FaultTree::CollectTopEvents(), scram::core::EventTreeAnalysis::EventTreeAnalysis(), scram::mef::cycle::GetConnectors(), and scram::mef::Serialize().
int scram::mef::Formula::num_args () const inline
Returns
The number of arguments.
Definition at line 263 of file event.h.
Referenced by Validate().
void scram::mef::Formula::AddArgument (EventArg event_arg)
Adds an event into the arguments list.
Parameters
[in] event_arg An argument event.
Exceptions
DuplicateArgumentError The argument event is duplicate.
Definition at line 93 of file event.cc.
References SCRAM_THROW.
Referenced by scram::core::EventTreeAnalysis::EventTreeAnalysis().
void scram::mef::Formula::AddArgument (FormulaPtr formula) inline
Adds a formula into the arguments list.
Formulas are unique.
Parameters
[in] formula A pointer to an argument formula.
Definition at line 276 of file event.h.
void scram::mef::Formula::RemoveArgument (EventArg event_arg)
Removes an event from the formula.
Parameters
[in] event_arg The argument event of this formula.
Exceptions
LogicError The argument does not belong to this formula.
Definition at line 105 of file event.cc.
References SCRAM_THROW.
void scram::mef::Formula::Validate () const
Checks if a formula is initialized correctly with the number of arguments.
Exceptions
ValidityError Problems with the operator or arguments.
Definition at line 112 of file event.cc.
References scram::mef::kNand, scram::mef::kNor, scram::mef::kNot, scram::mef::kNull, scram::mef::kOperatorToString, scram::mef::kVote, scram::mef::kXor, num_args(), and SCRAM_THROW.
The documentation for this class was generated from the following files:
event.h
event.cc