scram::Config Class Reference
scram::Config Class Reference
This class processes configuration files for analysis.
#include <config.h>
Public Member Functions
Config (const std::string &config_file)
A constructor with configurations for analysis.
const std::vector< std::string > & input_files () const
const core::Settings & settings () const
const std::string & output_path () const
Detailed Description
This class processes configuration files for analysis.
The class contains all the setup and state to initialize general analysis.
Definition at line 37 of file config.h.
Constructor & Destructor Documentation
scram::Config::Config (const std::string & config_file) explicit
A constructor with configurations for analysis.
Reads and validates the configurations.
All relative paths in the configuration are resolved with respect to the location of the original configuration file.
Parameters
[in] config_file The path to an XML file with configurations.
Exceptions
ValidityError The configurations have problems.
SettingsError Settings values contain errors.
IOError The file is not accessible.
Definition at line 57 of file config.cc.
References scram::core::Settings::algorithm(), scram::core::Settings::approximation(), scram::xml::Element::attribute(), scram::core::Settings::ccf_analysis(), scram::xml::Element::child(), scram::xml::Element::children(), scram::core::Settings::cut_off(), scram::core::Settings::importance_analysis(), input_files(), scram::core::Settings::limit_order(), scram::core::Settings::mission_time(), scram::xml::Element::name(), scram::core::Settings::num_bins(), scram::core::Settings::num_quantiles(), scram::core::Settings::num_trials(), scram::core::Settings::prime_implicants(), scram::core::Settings::probability_analysis(), scram::xml::Document::root(), scram::core::Settings::safety_integrity_levels(), SCRAM_THROW, scram::core::Settings::seed(), scram::core::Settings::time_step(), and scram::core::Settings::uncertainty_analysis().
Member Function Documentation
const std::vector<std::string>& scram::Config::input_files () const inline
Returns
normalized, absolute paths to input files for analysis.
Definition at line 53 of file config.h.
Referenced by Config().
const core::Settings& scram::Config::settings () const inline
Returns
the settings for analysis.
Definition at line 56 of file config.h.
const std::string& scram::Config::output_path () const inline
Returns
the output destination path (absolute, normalized).
empty string if no path has been set.
Definition at line 60 of file config.h.
The documentation for this class was generated from the following files:
config.h
config.cc