scram::mef::BasicEvent Class Reference
scram::mef::BasicEvent Class Reference
Representation of a basic event in a fault tree.
#include <event.h>
Public Member Functions
bool HasExpression () const
void expression (Expression *expression)
Sets the expression of this basic event.
Expression & expression () const
double p () const noexcept
void Validate () const
Validates the probability expressions for the primary event.
bool HasCcf () const
Indicates if this basic event has been set to be in a CCF group.
const Gate & ccf_gate () const
void ccf_gate (std::unique_ptr< Gate > gate)
Sets the common cause failure group gate that can represent this basic event in analysis with common cause information.
Public Member Functions inherited from scram::mef::Event
virtual ~Event ()=0
Abstract class.
Public Member Functions inherited from scram::mef::Id
Id (std::string name, std::string base_path="", RoleSpecifier role=RoleSpecifier::kPublic)
Constructs an element with an original name.
const std::string & id () const
void id (std::string name)
Resets the element ID.
Public Member Functions inherited from scram::mef::Element
Element (std::string name)
Constructs an element with an original name.
const std::string & name () const
const std::string & label () const
void label (std::string label)
Sets the label.
const std::vector< Attribute > & attributes () const
void AddAttribute (Attribute attr)
Adds an attribute to the attribute map.
void SetAttribute (Attribute attr)
Sets an attribute to the attribute map.
bool HasAttribute (const std::string &name) const
Checks if the element has a given attribute.
const Attribute & GetAttribute (const std::string &name) const
bool RemoveAttribute (const std::string &name)
Removes the attribute of the element.
Public Member Functions inherited from scram::mef::Role
Role (RoleSpecifier role=RoleSpecifier::kPublic, std::string base_path="")
Sets the role of an element upon creation.
RoleSpecifier role () const
const std::string & base_path () const
Public Member Functions inherited from scram::mef::Usage
bool usage () const
void usage (bool usage)
Additional Inherited Members
Static Public Member Functions inherited from scram::mef::Id
static const std::string & unique_name (const Element &element)
Produces unique name for the model element within the same type.
static const std::string & unique_name (const Id &element)
Produces unique name for the model element within the same type.
Protected Member Functions inherited from scram::mef::Element
void name (std::string name)
Resets the element name.
Detailed Description
Representation of a basic event in a fault tree.
Definition at line 75 of file event.h.
Member Function Documentation
bool scram::mef::BasicEvent::HasExpression () const inline
Returns
true if the probability expression is set.
Definition at line 82 of file event.h.
Referenced by scram::mef::Initializer::Define(), and scram::mef::Serialize().
void scram::mef::BasicEvent::expression (Expression * expression) inline
Sets the expression of this basic event.
Parameters
[in] expression The expression to describe this event. nullptr to remove unset the expression.
Definition at line 88 of file event.h.
References expression().
Referenced by scram::mef::Initializer::Define(), expression(), and scram::mef::Serialize().
Expression& scram::mef::BasicEvent::expression () const inline
Returns
The previously set expression for analysis purposes.
Precondition
The expression has been set.
Definition at line 93 of file event.h.
double scram::mef::BasicEvent::p () const inline noexcept
Returns
The mean probability of this basic event.
Precondition
The expression has been set.
Note
The user of this function should make sure that the returned value is acceptable for calculations.
Definition at line 104 of file event.h.
Referenced by scram::core::ImportanceAnalysis::Analyze(), and scram::core::Product::p().
void scram::mef::BasicEvent::Validate () const
Validates the probability expressions for the primary event.
Precondition
The probability expression is set.
Exceptions
DomainError The expression for the basic event is invalid.
Definition at line 40 of file event.cc.
References scram::mef::EnsureProbability(), and scram::mef::Element::name().
Referenced by scram::mef::CcfGroup::members().
bool scram::mef::BasicEvent::HasCcf () const inline
Indicates if this basic event has been set to be in a CCF group.
Returns
true if in a CCF group.
Definition at line 119 of file event.h.
const Gate& scram::mef::BasicEvent::ccf_gate () const inline
Returns
CCF group gate representing this basic event.
Definition at line 122 of file event.h.
void scram::mef::BasicEvent::ccf_gate (std::unique_ptr< Gate > gate) inline
Sets the common cause failure group gate that can represent this basic event in analysis with common cause information.
This information is expected to be provided by CCF group application.
Parameters
[in] gate CCF group gate.
Definition at line 134 of file event.h.
The documentation for this class was generated from the following files:
event.h
event.cc