scram::mef::Gate Class Reference
scram::mef::Gate Class Reference
A representation of a gate in a fault tree.
#include <event.h>
Public Member Functions
bool HasFormula () const
FormulaPtr formula (FormulaPtr formula)
Sets the formula of this gate.
void Validate () const
Checks if a gate is initialized correctly.
const Formula & formula () const
Formula & formula ()
Public Member Functions inherited from scram::mef::Event
virtual ~Event ()=0
Abstract class.
Public Member Functions inherited from scram::mef::Id
Id (std::string name, std::string base_path="", RoleSpecifier role=RoleSpecifier::kPublic)
Constructs an element with an original name.
const std::string & id () const
void id (std::string name)
Resets the element ID.
Public Member Functions inherited from scram::mef::Element
Element (std::string name)
Constructs an element with an original name.
const std::string & name () const
const std::string & label () const
void label (std::string label)
Sets the label.
const std::vector< Attribute > & attributes () const
void AddAttribute (Attribute attr)
Adds an attribute to the attribute map.
void SetAttribute (Attribute attr)
Sets an attribute to the attribute map.
bool HasAttribute (const std::string &name) const
Checks if the element has a given attribute.
const Attribute & GetAttribute (const std::string &name) const
bool RemoveAttribute (const std::string &name)
Removes the attribute of the element.
Public Member Functions inherited from scram::mef::Role
Role (RoleSpecifier role=RoleSpecifier::kPublic, std::string base_path="")
Sets the role of an element upon creation.
RoleSpecifier role () const
const std::string & base_path () const
Public Member Functions inherited from scram::mef::Usage
bool usage () const
void usage (bool usage)
Public Member Functions inherited from scram::mef::NodeMark
Mark mark () const
void mark (Mark label)
Sets the mark for this node.
Additional Inherited Members
Public Types inherited from scram::mef::NodeMark
enum Mark : std::uint8_t { kClear = 0, kTemporary, kPermanent }
Possible marks for the node.
Static Public Member Functions inherited from scram::mef::Id
static const std::string & unique_name (const Element &element)
Produces unique name for the model element within the same type.
static const std::string & unique_name (const Id &element)
Produces unique name for the model element within the same type.
Protected Member Functions inherited from scram::mef::Element
void name (std::string name)
Resets the element name.
Detailed Description
A representation of a gate in a fault tree.
Definition at line 161 of file event.h.
Member Function Documentation
bool scram::mef::Gate::HasFormula () const inline
Returns
true if the gate formula has been set.
Definition at line 166 of file event.h.
Referenced by scram::mef::Initializer::Define().
const Formula& scram::mef::Gate::formula () const inline
Returns
The formula of this gate.
Precondition
The gate has its formula initialized.
Definition at line 173 of file event.h.
Referenced by scram::mef::FaultTree::CollectTopEvents(), scram::mef::Initializer::Define(), scram::core::EventTreeAnalysis::EventTreeAnalysis(), scram::mef::cycle::GetConnector(), and scram::mef::Serialize().
Formula& scram::mef::Gate::formula () inline
Returns
The formula of this gate.
Precondition
The gate has its formula initialized.
Definition at line 177 of file event.h.
FormulaPtr scram::mef::Gate::formula (FormulaPtr formula) inline
Sets the formula of this gate.
Parameters
[in] formula The new Boolean formula of this gate.
Returns
The old formula.
Definition at line 187 of file event.h.
void scram::mef::Gate::Validate () const
Checks if a gate is initialized correctly.
Precondition
The gate formula is set.
Exceptions
ValidityError Errors in the gate's logic or setup.
Definition at line 45 of file event.cc.
References scram::mef::Element::GetAttribute(), scram::mef::Element::HasAttribute(), scram::mef::Element::name(), SCRAM_THROW, and scram::mef::Attribute::value.
Referenced by scram::mef::Initializer::Define().
The documentation for this class was generated from the following files:
event.h
event.cc