scram::mef::Component Class Reference
scram::mef::Component Class Reference
Component is for logical grouping of events, gates, and other components.
#include <fault_tree.h>
Public Member Functions
Component (std::string name, std::string base_path="", RoleSpecifier role=RoleSpecifier::kPublic)
Constructs a component assuming that it exists within some fault tree.
const ElementTable< Gate * > & gates () const
const ElementTable< BasicEvent * > & basic_events () const
const ElementTable< HouseEvent * > & house_events () const
const ElementTable< Parameter * > & parameters () const
const ElementTable< CcfGroup * > & ccf_groups () const
const ElementTable< std::unique_ptr< Component > > & components () const
void Add (Gate *element)
Adds MEF constructs into this component container.
void Add (BasicEvent *element)
Adds MEF constructs into this component container.
void Add (HouseEvent *element)
Adds MEF constructs into this component container.
void Add (Parameter *element)
Adds MEF constructs into this component container.
void Add (CcfGroup *element)
Adds MEF constructs into this component container.
void Add (std::unique_ptr< Component > element)
Adds MEF constructs into this component container.
void Remove (HouseEvent *element)
Removes Event from the component container.
void Remove (BasicEvent *element)
Removes Event from the component container.
void Remove (Gate *element)
Removes Event from the component container.
Public Member Functions inherited from scram::mef::Element
Element (std::string name)
Constructs an element with an original name.
const std::string & name () const
const std::string & label () const
void label (std::string label)
Sets the label.
const std::vector< Attribute > & attributes () const
void AddAttribute (Attribute attr)
Adds an attribute to the attribute map.
void SetAttribute (Attribute attr)
Sets an attribute to the attribute map.
bool HasAttribute (const std::string &name) const
Checks if the element has a given attribute.
const Attribute & GetAttribute (const std::string &name) const
bool RemoveAttribute (const std::string &name)
Removes the attribute of the element.
Public Member Functions inherited from scram::mef::Role
Role (RoleSpecifier role=RoleSpecifier::kPublic, std::string base_path="")
Sets the role of an element upon creation.
RoleSpecifier role () const
const std::string & base_path () const
Protected Member Functions
void GatherGates (std::unordered_set< Gate * > *gates)
Recursively traverses components to gather gates relevant to the whole component.
Protected Member Functions inherited from scram::mef::Element
void name (std::string name)
Resets the element name.
Detailed Description
Component is for logical grouping of events, gates, and other components.
Definition at line 36 of file fault_tree.h.
Constructor & Destructor Documentation
scram::mef::Component::Component (std::string name, std::string base_path = "", RoleSpecifier role = RoleSpecifier::kPublic) explicit
Constructs a component assuming that it exists within some fault tree.
The public or private role of a component is not for the components itself, but for the events and parameters of the component. Component name is not meant to be public; however, it must be unique within the parent fault tree or component.
Parameters
[in] name The name identifier for the component.
[in] base_path The series of containers to get this container.
[in] role The default role for container members.
Exceptions
LogicError The name is empty.
ValidityError The name or reference paths are malformed.
Definition at line 27 of file fault_tree.cc.
Member Function Documentation
const ElementTable<Gate*>& scram::mef::Component::gates () const inline
Returns
The container of component constructs of specific kind with construct original names as keys.
Definition at line 60 of file fault_tree.h.
Referenced by scram::mef::FaultTree::CollectTopEvents(), components(), scram::mef::Serialize(), and scram::mef::FaultTree::top_events().
const ElementTable<BasicEvent*>& scram::mef::Component::basic_events () const inline
Returns
The container of component constructs of specific kind with construct original names as keys.
Definition at line 61 of file fault_tree.h.
const ElementTable<HouseEvent*>& scram::mef::Component::house_events () const inline
Returns
The container of component constructs of specific kind with construct original names as keys.
Definition at line 64 of file fault_tree.h.
const ElementTable<Parameter*>& scram::mef::Component::parameters () const inline
Returns
The container of component constructs of specific kind with construct original names as keys.
Definition at line 67 of file fault_tree.h.
const ElementTable<CcfGroup*>& scram::mef::Component::ccf_groups () const inline
Returns
The container of component constructs of specific kind with construct original names as keys.
Definition at line 68 of file fault_tree.h.
const ElementTable<std::unique_ptr<Component> >& scram::mef::Component::components () const inline
Returns
The container of component constructs of specific kind with construct original names as keys.
Definition at line 69 of file fault_tree.h.
References Add(), gates(), GatherGates(), and Remove().
Referenced by scram::mef::Serialize().
void scram::mef::Component::Add (Gate * element)
Adds MEF constructs into this component container.
Parameters
[in] element The element to be added to the container.
Exceptions
ValidityError The element is already in this container.
Definition at line 31 of file fault_tree.cc.
Referenced by components(), and scram::mef::Initializer::Define().
void scram::mef::Component::Add (BasicEvent * element)
Adds MEF constructs into this component container.
Parameters
[in] element The element to be added to the container.
Exceptions
ValidityError The element is already in this container.
Definition at line 33 of file fault_tree.cc.
void scram::mef::Component::Add (HouseEvent * element)
Adds MEF constructs into this component container.
Parameters
[in] element The element to be added to the container.
Exceptions
ValidityError The element is already in this container.
Definition at line 37 of file fault_tree.cc.
void scram::mef::Component::Add (Parameter * element)
Adds MEF constructs into this component container.
Parameters
[in] element The element to be added to the container.
Exceptions
ValidityError The element is already in this container.
Definition at line 41 of file fault_tree.cc.
void scram::mef::Component::Add (CcfGroup * element)
Adds MEF constructs into this component container.
Parameters
[in] element The element to be added to the container.
Exceptions
ValidityError The element is already in this container.
Definition at line 46 of file fault_tree.cc.
References scram::mef::CcfGroup::members(), scram::mef::Element::name(), and SCRAM_THROW.
void scram::mef::Component::Add (std::unique_ptr< Component > element)
Adds MEF constructs into this component container.
Parameters
[in] element The element to be added to the container.
Exceptions
ValidityError The element is already in this container.
Definition at line 63 of file fault_tree.cc.
References SCRAM_THROW.
void scram::mef::Component::Remove (HouseEvent * element)
Removes Event from the component container.
Parameters
[in] element An element defined in this model.
Exceptions
UndefinedElement The element doesn't belong to this container.
Definition at line 87 of file fault_tree.cc.
Referenced by components().
void scram::mef::Component::Remove (BasicEvent * element)
Removes Event from the component container.
Parameters
[in] element An element defined in this model.
Exceptions
UndefinedElement The element doesn't belong to this container.
Definition at line 91 of file fault_tree.cc.
void scram::mef::Component::Remove (Gate * element)
Removes Event from the component container.
Parameters
[in] element An element defined in this model.
Exceptions
UndefinedElement The element doesn't belong to this container.
Definition at line 95 of file fault_tree.cc.
void scram::mef::Component::GatherGates (std::unordered_set< Gate * > * gates) protected
Recursively traverses components to gather gates relevant to the whole component.
Parameters
[out] gates Gates belonging to this component and its subcomponents.
Definition at line 97 of file fault_tree.cc.
References scram::mef::Element::name(), and SCRAM_THROW.
Referenced by scram::mef::FaultTree::CollectTopEvents(), and components().
The documentation for this class was generated from the following files:
fault_tree.h
fault_tree.cc