scram::mef::Alignment Class Reference
scram::mef::Alignment Class Reference
Alignment configuration for the whole model per analysis.
#include <alignment.h>
Public Member Functions
const ElementTable< PhasePtr > & phases () const
void Add (PhasePtr phase)
Adds a phase into alignment.
void Validate ()
Ensures that all phases add up to be valid for the alignment.
Public Member Functions inherited from scram::mef::Element
Element (std::string name)
Constructs an element with an original name.
const std::string & name () const
const std::string & label () const
void label (std::string label)
Sets the label.
const std::vector< Attribute > & attributes () const
void AddAttribute (Attribute attr)
Adds an attribute to the attribute map.
void SetAttribute (Attribute attr)
Sets an attribute to the attribute map.
bool HasAttribute (const std::string &name) const
Checks if the element has a given attribute.
const Attribute & GetAttribute (const std::string &name) const
bool RemoveAttribute (const std::string &name)
Removes the attribute of the element.
Additional Inherited Members
Protected Member Functions inherited from scram::mef::Element
void name (std::string name)
Resets the element name.
Detailed Description
Alignment configuration for the whole model per analysis.
Definition at line 63 of file alignment.h.
Member Function Documentation
const ElementTable<PhasePtr>& scram::mef::Alignment::phases () const inline
Returns
The phases defined in the alignment.
Definition at line 68 of file alignment.h.
void scram::mef::Alignment::Add (PhasePtr phase)
Adds a phase into alignment.
Parameters
[in] phase One of the unique phases for the alignment.
Exceptions
DuplicateArgumentError The phase is duplicate.
Definition at line 34 of file alignment.cc.
Referenced by scram::mef::Initializer::Define().
void scram::mef::Alignment::Validate ()
Ensures that all phases add up to be valid for the alignment.
Exceptions
ValidityError Phases are incomplete (e.g., don't sum to 1).
Definition at line 39 of file alignment.cc.
References scram::mef::Element::name(), and SCRAM_THROW.
Referenced by scram::mef::Initializer::Define().
The documentation for this class was generated from the following files:
alignment.h
alignment.cc