expression.h File Reference
expression.h File Reference
Provides the base class for all expressions and units for expression values.
#include <algorithm>
#include <string>
#include <utility>
#include <vector>
#include <boost/icl/continuous_interval.hpp>
#include <boost/noncopyable.hpp>
Classes
class scram::mef::Expression
Abstract base class for all sorts of expressions to describe events.
class scram::mef::ExpressionFormula< T >
CRTP for Expressions with the same formula to evaluate and sample.
class scram::mef::NaryExpression< T, N >
n-ary expressions.
class scram::mef::NaryExpression< T, 1 >
Unary expression.
class scram::mef::NaryExpression< T, 2 >
Binary expression.
class scram::mef::NaryExpression< T,-1 >
Multivariate expression.
Typedefs
using scram::mef::Interval = boost::icl::continuous_interval< double >
Validation domain interval for expression values.
using scram::mef::IntervalBounds = boost::icl::interval_bounds
left_open, open, right_open, closed bounds.
Functions
bool scram::mef::Contains (const Interval &interval, double value)
Returns true if a given interval contains a given value.
bool scram::mef::IsProbability (const Interval &interval)
Checks if a given interval is within the probability domain.
bool scram::mef::IsNonNegative (const Interval &interval)
Checks if all values in a given interval are non-negative.
bool scram::mef::IsPositive (const Interval &interval)
Checks if all values in a given interval are positive.
void scram::mef::detail::EnsureMultivariateArgs (std::vector< Expression * > args)
Ensures the number of args for multivariate expressions.
void scram::mef::EnsureProbability (Expression *expression, const std::string &description, const char *type="probability")
Ensures that expression can be used for probability ([0, 1]).
void scram::mef::EnsurePositive (Expression *expression, const std::string &description)
Ensures that expression yields positive (> 0) values.
void scram::mef::EnsureNonNegative (Expression *expression, const std::string &description)
Ensures that expression yields non-negative (>= 0) values.
void scram::mef::EnsureWithin (Expression *expression, const Interval &interval, const char *type)
Ensures that expression values are within the interval.
Detailed Description
Provides the base class for all expressions and units for expression values.
Definition in file expression.h.
Typedef Documentation
using scram::mef::IntervalBounds = typedef boost::icl::interval_bounds
left_open, open, right_open, closed bounds.
Todo:
Interval bound propagation upon operations on boundary values.
Definition at line 38 of file expression.h.
Function Documentation
void scram::mef::detail::EnsureMultivariateArgs (std::vector< Expression * > args)
Ensures the number of args for multivariate expressions.
Parameters
[in] args Argument expressions.
Exceptions
ValidityError The number of arguments is fewer than 2.
Definition at line 55 of file expression.cc.
References scram::mef::detail::EnsureMultivariateArgs(), and SCRAM_THROW.
Referenced by scram::mef::detail::EnsureMultivariateArgs().
void scram::mef::EnsureProbability (Expression * expression, const std::string & description, const char * type = "probability")
Ensures that expression can be used for probability ([0, 1]).
Parameters
[in] expression The expression to be validated.
[in] description The addition information for error messages.
[in] type The type of probability or fraction for error messages.
Exceptions
DomainError The expression is not suited for probability.
Definition at line 62 of file expression.cc.
References scram::mef::EnsureProbability(), scram::mef::Expression::interval(), scram::mef::IsProbability(), SCRAM_THROW, and scram::mef::Expression::value().
Referenced by scram::mef::NaryExpression< T,-1 >::Compute(), scram::mef::EnsureProbability(), scram::mef::PeriodicTest::PeriodicTest(), scram::mef::Glm::Validate(), scram::mef::BasicEvent::Validate(), and scram::mef::CcfGroup::Validate().
void scram::mef::EnsurePositive (Expression * expression, const std::string & description)
Ensures that expression yields positive (> 0) values.
Parameters
[in] expression The expression to be validated.
[in] description The addition information for error messages.
Exceptions
DomainError The expression is not suited for positive values.
Definition at line 74 of file expression.cc.
References scram::mef::EnsurePositive(), scram::mef::Expression::interval(), scram::mef::IsPositive(), SCRAM_THROW, and scram::mef::Expression::value().
Referenced by scram::mef::Mean::Compute(), scram::mef::NaryExpression< T,-1 >::Compute(), scram::mef::EnsurePositive(), scram::mef::PeriodicTest::PeriodicTest(), scram::mef::Glm::Validate(), and scram::mef::Weibull::Validate().
void scram::mef::EnsureNonNegative (Expression * expression, const std::string & description)
Ensures that expression yields non-negative (>= 0) values.
Parameters
[in] expression The expression to be validated.
[in] description The addition information for error messages.
Exceptions
DomainError The expression is not suited for non-negative values.
Definition at line 82 of file expression.cc.
References scram::mef::EnsureNonNegative(), scram::mef::Expression::interval(), scram::mef::IsNonNegative(), SCRAM_THROW, and scram::mef::Expression::value().
Referenced by scram::mef::Mean::Compute(), scram::mef::NaryExpression< T,-1 >::Compute(), scram::mef::EnsureNonNegative(), scram::mef::PeriodicTest::PeriodicTest(), scram::mef::Exponential::Validate(), scram::mef::Glm::Validate(), and scram::mef::Weibull::Validate().
void scram::mef::EnsureWithin (Expression * expression, const Interval & interval, const char * type)
Ensures that expression values are within the interval.
Parameters
[in] expression The expression to be validated.
[in] interval The allowed interval.
[in] type The type of expression for error messages.
Exceptions
DomainError The expression is not suited for non-negative values.
Definition at line 91 of file expression.cc.
References scram::mef::Contains(), scram::mef::EnsureWithin(), scram::mef::Expression::interval(), SCRAM_THROW, and scram::mef::Expression::value().
Referenced by scram::mef::Mean::Compute(), scram::mef::NaryExpression< T,-1 >::Compute(), and scram::mef::EnsureWithin().