version.h File Reference
version.h File Reference
Set of functions with version information of the core and dependencies.
Functions
const char * scram::version::describe ()
const char * scram::version::build ()
const char * scram::version::core ()
const char * scram::version::boost ()
const char * scram::version::libxml ()
Detailed Description
Set of functions with version information of the core and dependencies.
Definition in file version.h.
Function Documentation
const char * scram::version::describe ()
Returns
Git generated tag recent version.
Definition at line 32 of file version.cc.in.
References scram::version::describe().
Referenced by scram::version::describe().
const char * scram::version::build ()
Returns
Build type.
Definition at line 34 of file version.cc.in.
References scram::version::build().
Referenced by scram::version::build().
const char * scram::version::core ()
Returns
The core version.
Definition at line 37 of file version.cc.in.
References scram::version::core().
Referenced by scram::version::core().
const char * scram::version::boost ()
Returns
The version of the boost.
Definition at line 42 of file version.cc.in.
References scram::version::boost().
Referenced by scram::version::boost().
const char * scram::version::libxml ()
Returns
The version of the XML C library.
Definition at line 44 of file version.cc.in.
References scram::version::libxml().
Referenced by scram::version::libxml().